name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: apt-update
      run: sudo apt-get update
    - name: install build tool
      run: sudo apt-get install gcc-arm-none-eabi
    - name: install crcmod
      run: python3 -m pip install crcmod
    - name: make
      run: make
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          bin/firmware.bin
          bin/firmware.packed.bin
          bin/firmware
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/firmware.bin
          bin/firmware.packed.bin
